# ─── Auth Service Configuration ───────────────────────────────
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/messenger_db?currentSchema=auth_schema
    username: messenger
    password: messenger_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: auth_schema
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# ─── JWT Configuration ──────────────────────────────────────
app:
  jwt:
    secret: "YTJiM2M0ZDVlNmY3ZzhpOWoxazJsM200bjVvNnA3cThyOXMwdDF1MnYzdzR4NXk2ejdBMkIzQzRENUU2Rjc="
    access-token-expiration-ms: 900000       # 15 minutes
    refresh-token-expiration-ms: 604800000   # 7 days

# ─── Redis ──────────────────────────────────────────────────
  redis:
    host: localhost
    port: 6379
    password: redis_secret
