spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/messenger_db?currentSchema=messaging_schema
    username: messenger
    password: messenger_secret
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: messaging_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: messaging_schema
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: messaging-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.enterprise.messenger.common.dto.messaging
      auto-offset-reset: earliest

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
